blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Support/Usage Question
    url: https://community.openhab.org
    about: Feel free to ask anything
  - name: ðŸ“– Documentation
    url: https://openhab.org/addons
    about: Official documentation
  - name: ðŸ“š Translation feedback
    url: https://crowdin.com/project/openhab2-addons
    about: Share feedback on translations
