name: 'Stale issues check'

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    name: Stale issues check
    permissions:
      issues: write
    steps:
      - name: Stale issues check
        uses: actions/stale@v10
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 180
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-labels: 'awaiting feedback'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,PR pending'
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
